### ISSUE TITLE
Still getting blank electron on `npm start`

### ISSUE THREAD

**Issue by evbogue** [dominictarr/patchdeck#4]
Screenshot below.

![2016-03-29-155955_1366x768_scrot](https://cloud.githubusercontent.com/assets/2468866/14121970/a5815f52-f5c7-11e5-865f-b6aa65a39645.png)

**Comment by dominictarr** [comment]
hmm, do you get any errors in the dev console? (ctrl-shift-i)

**Comment by evbogue** [comment]
Ok, I was missing three dependencies.

They are: observable, pull-scroll, ssb-markdown. Now it's working!

**Comment by dominictarr** [comment]
okay I added the deps, and published in 0.0.2
it doesn't run for long though, because the local connection gets cut off after 30 seconds.
this is fixed in a dev branch of ssb, but it's not merged yet. (try setting `ssb_timeout=0`, that might work if you have a recent enough scuttlebot. anyway, I'll try and get this running properly this weekend!
